version: "3.4"

x-logging:
    &default-logging
    driver: "json-file"
    options:
      tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:

  app:
    image: vadimkerr/devops-uni:latest
    ports:
      - "8000:8000"
    logging: *default-logging

  grafana:
    image: grafana/grafana:8.1.3
    ports:
      - "3000:3000"
    logging: *default-logging

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging: *default-logging

  promtail:
    image: grafana/promtail:2.3.0
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${PWD}/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    logging: *default-logging
