version: "3.4"

x-logging:
    &default-logging
    driver: "json-file"
    options:
      tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
      max-size: "20m"
      max-file: "3"

x-resource-limits:
  &default-resource-limits
  mem_limit: 300M

x-common-params:
  &common-params
  logging: *default-logging
  <<: *default-resource-limits

volumes:
  app-data:

services:

  app:
    image: vadimkerr/devops-uni:latest
    ports:
      - "8000:8000"
    volumes:
      - app-data:/app/data
    <<: *common-params

  grafana:
    image: grafana/grafana:8.1.3
    ports:
      - "3000:3000"
    <<: *common-params

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    <<: *common-params

  promtail:
    image: grafana/promtail:2.3.0
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${PWD}/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    <<: *common-params

  prometheus:
    image: prom/prometheus:v2.30.0-rc.0
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    <<: *common-params
