scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "loki"
    scrape_interval: 10s
    static_configs:
      - targets: ["loki:3100"]
