# Default values for devops-uni.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: vadimkerr/devops-uni
  pullPolicy: IfNotPresent
  tag: latest
  port: 8000

service:
  type: LoadBalancer
  port: 8000

secret:
  name: app-secret
  password: SuperSecretPassword123

resources:
  requests:
    cpu: "250m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"

ingress:
  enabled: false

autoscaling:
  enabled: false
