name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        run: echo test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: pre-commit
        uses: pre-commit/action@v2.0.3

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: fake test
        run: echo Fake tests are passing!
